name: Sync Upstream Twilight Release
on:
  schedule:
    - cron: '0 * * * *'
  workflow_dispatch:

jobs:
  sync-upstream:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    outputs:
      needs_update: ${{ steps.check-version.outputs.needs_update }}
    steps:
      - uses: actions/checkout@v4

      - name: check for new upstream version
        id: check-version
        run: |
          LOCAL_VER=$(grep -oP 'Version:\s*\K.*' zen-browser-twilight.spec)
          echo "Local version: $LOCAL_VER"

          # get latest pre-release version from github
          # we have to extract the build version from the name as the tag is just "twilight"
          # twilight builds are re-released with the same version number sometimes so we add the timestampe to the version
          TWILIGTH=$(curl -s https://api.github.com/repos/zen-browser/desktop/releases | jq -r 'map(select(.prerelease)) | first | .name')
          TWILIGHT_VER=$(echo $TWILIGTH | grep -oP 'Twilight build - \K.*(?=\s\()' | sed 's@-@.@g')
          BUILD_TIMESTAMP=$(echo $TWILIGTH | grep -oP '\(\K.*(?=\))' | sed 's@ at @@g' | sed 's@-@@g' | sed 's@:@@g')
          TWILIGHT_VER_SPEC="$TWILIGHT_VER.$BUILD_TIMESTAMP"

          NEEDS_UPDATE=false
          if [ "$LOCAL_VER" != "$TWILIGHT_VER_SPEC" ]; then
            NEEDS_UPDATE=true
          fi

          echo "TWILIGHT_VER_SPEC=$TWILIGHT_VER_SPEC" >> $GITHUB_ENV
          echo "needs_update=$NEEDS_UPDATE" >> $GITHUB_OUTPUT

      - name: Setup git bot
        if: steps.check-version.outputs.needs_update == 'true'
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

      - name: Update zen-browser-twilight.spec
        if: steps.check-version.outputs.needs_update == 'true'
        run: |
          # update spec file version and url
          sed -i '0,/Version:.*/s//Version:            '$TWILIGHT_VER_SPEC'/' zen-browser-twilight.spec

          COMMIT_MSG="Update to upstream release $TWILIGHT_VER_SPEC"
          CHANGELOG="$(sed -n '/%changelog/,$p' zen-browser-twilight.spec | sed '1d')"
          NEW_CHANGELOG=$(echo -e "* $(date +'%a %b %d %Y') ArchitektApx <architektapx@gehinors.ch> - $TWILIGHT_VER_SPEC\n- $COMMIT_MSG\n\n$CHANGELOG")

          # replace old changelog with new one
          sed -i '/%changelog/,$d' zen-browser-twilight.spec
          echo -e "%changelog\n$NEW_CHANGELOG" >> zen-browser-twilight.spec
          git add zen-browser-twilight.spec

      - name: commit and tag new version
        if: steps.check-version.outputs.needs_update == 'true'
        id: commit-update
        run: |
          git commit -m "chore(zen-browser-twilight): Sync twilight spec to $TWILIGHT_VER_SPEC"
          git push